apiVersion: v1
kind: ConfigMap
metadata:
  name: inli-config-map
  namespace: inli-ns
  labels:
    app: inli-app
data:
  BASE_LINK: https://www.inli.fr
  SLEEP_MIN: "5"
  SLEEP_MAX: "10"
  INLI_URL: toPatch
  PLACE_NAME: toPatch