apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Ordre d'application des ressources
resources:
  - Namespace.yaml
  - ConfigMap.yaml
  - SealedSecrets.yaml
  - Deployment.yaml
  - PersistentVolumeClaim.yaml

# Labels communs Ã  toutes les ressources
commonLabels:
  app: inli-app
  managed-by: argocd

# Annotations communes
commonAnnotations:
  argocd.argoproj.io/sync-wave: "0"
