apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Render the overlay(s) from this root so Argo CD can point to `inli-app` directly.
resources:
  - overlays/essonne
#   - overlays/another-environment
