apiVersion: v1
kind: ConfigMap
metadata:
  name: inli-config-map
  namespace: inli-ns
data:
  INLI_URL: https://inli.fr/locations/offres/essonne-departement_d:91?price_min=&price_max=800&area_min=30&area_max=&room_min=1&room_max=5&bedroom_min=1&bedroom_max=5
  PLACE_NAME: Essonne