apiVersion: apps/v1
kind: Deployment
metadata:
  name: inli-deployment
  namespace: inli-ns
spec:
  template:
    spec:
      containers:
      - name: inli-pod
        envFrom:
        - secretRef:
            name: inli-secret-essonne
