apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -essonne

resources:
  - ../../base

commonLabels:
  ns: inli-ns-essonne

patches:
  - path: ConfigMap-essonne.yaml
  - path: Deployment-essonne.yaml
  